name: TypeScript Compile Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Compiling
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
        node-version: 17
      - run: npm ci
      - run: npm i typescript
      - run: npm run build